config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index', via: :get
  devise_for :users
  get 'home/index'
  get 'home/search'
  get 'home/episodes'
  post 'add_favorite/:tvdb_id', to: 'home#add_favorite', as: 'add_to_favorites'
  delete 'remove_favorite/:tvdb_id', to: 'home#remove_favorite', as: 'remove_from_favorites'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :series
  belongs_to :season

  validates_presence_of :title
  validates_presence_of :air_date

  scope :todays_episodes, -> { where(air_date: Date.today) }

  def episode_code
    'S%02iE%02i' % [self.season.number, self.episode_number]
  end

  def formated_air_date
    self.air_date.strftime('%d %b, %Y')
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :series
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/season.rb
class Season < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :number

  before_validation :set_season_name


  private

  def set_season_name
    self.name = "Season #{self.number}"
  end
 
end

app/models/series.rb
class Series < ApplicationRecord

  after_commit :update_remaining_data, on: :create

  validates_presence_of :tvdb_id

  has_many :favorites
  has_many :users, through: :favorites
  has_many :episodes


  def update_from_api_data(data)
    self.update({
      name: data['seriesName'],
      status: data['status'],
      overview: data['overview'],
      tvdb_id: data['id'],
      network: data['network'],
      first_aired: data['firstAired'],
      genre: data['genre']
    })
  end

  def has_new_episode?(updated_episodes_count)
    self.episodes.count < updated_episodes_count
  end

  def self.parse_api_data(api_data)
    parsed_data = api_data
    Series.new(parsed_data)
  end


  private

  def update_remaining_data
    SeriesUpdateJob.perform_later(self.id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites
  has_many :series, through: :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  before_action :configure_signup_parameters, if: :devise_controller?


  private

  def layout_by_resource
    if devise_controller?
      'devise'   
    else
      'application'
    end
  end

 def configure_signup_parameters
   devise_parameter_sanitizer.permit(:sign_up) do |user_params|
     user_params.permit(:email, :name, :password, :password_confirmation)
   end
 end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_action :authenticate_user!, only: [:add_favorite, :remove_favorite]

  def index
    if current_user
      @series = current_user.series
    else
      @series = Series.all
    end
  end

  def episodes
    @series = Series.find_by(tvdb_id: params[:id])
    if @series.nil?
      api = Episodes.new
      seasons, series_data = api.call(params[:id])
      @series = Series.new(name: series_data['seriesName'], overview: series_data['overview'], genre: series_data['genre'], tvdb_id: series_data['id'])
      @seasons = seasons.map do |season, episodes|
        [
          season,
          episodes.map {|episode| Episode.new({
            episode_number: episode['airedEpisodeNumber'],
            title: episode['episodeName'],
            overview: episode['overview']
          })}
        ]
      end
    else
      @seasons = @series.episodes.eager_load(:season).group_by {|ep| ep.season.number}.sort 
    end
    if current_user
      @in_favorites = current_user.series.exists?(tvdb_id: params[:id])
    end
  end

  def search
    if params[:q].present?
      api = Search.new
      results = api.call(params[:q]) 
      if results['data']
        @series = results['data'].map{|series_data| Series.new({
                                                                  name: series_data['seriesName'],
                                                                  status: series_data['status'],
                                                                  overview: series_data['overview'],
                                                                  tvdb_id: series_data['id'],
                                                                  network: series_data['network'],
                                                                  first_aired: series_data['firstAired']
                                                                  })}
      else
        @series = []
      end
    else
      redirect_to request.referrer
    end
  end

  def add_favorite
    series = Series.find_or_create_by(tvdb_id: params[:tvdb_id])  
    added_favorite = current_user.favorites.find_or_create_by(series_id: series.id)
    render json: {}
  end

  def remove_favorite
    series = Series.find_or_create_by(tvdb_id: params[:tvdb_id])  
    favorite = current_user.favorites.find_by(series_id: series.id)
    favorite.destroy
    render json: {}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_episode.html.haml
.panel.panel-default
  .panel-heading
    %h4= "#{episode.episode_number}. #{episode.title} (#{episode.formated_air_date})"
  .panel-body= episode.overview

app/views/home/_series.html.haml
.panel.panel-default
  .panel-heading
    = link_to series.name, url_for(controller: 'home', action: 'episodes', id: series.tvdb_id, only_path: true) 
    - if series.status == 'Ended'
      %span.label.label-danger= series.status
    - else
      %span.label.label-success= series.status
  .panel-body= (series.overview || 'Overview not available')
    

app/views/home/_series_list.html.haml
- series_list.each do |series|
  = render 'series', series: series

app/views/home/episodes.html.haml
.container
  .jumbotron
    %h2= @series.name
    %p= @series.overview
    .row
      .col-lg-6
        %div 
          %strong Genre:
        %div= @series.genre.join(', ')
      .col-lg-6
        - if @in_favorites
          = link_to 'Remove from Favorites', remove_from_favorites_path(@series['id']), remote: true, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'
        - else
          = link_to 'Add to Favorites', add_to_favorites_path(@series.tvdb_id), remote: true, method: :post, class: 'btn btn-success'

  .row
    %h3 Episodes
  .row
    .panel-group
      - @seasons.each do |season, episodes|
        .panel-default.panel
          .panel-heading
            %h4= link_to "Season #{season}", "#season#{season}", data: {toggle: 'collapse'}
          .panel-collapse.collapse{id: "season#{season}"}
            .panel-body
              - episodes.sort.each do |episode|
                = render 'episode', episode: episode

app/views/home/genre.html.haml
%h1 Home#genre
%p Find me in app/views/home/genre.html.erb

app/views/home/index.html.haml
.container-fluid
  .col-lg-10.col-lg-offset-1
    - if user_signed_in?
      %h1 Your favorite shows
      - if @series.any?
        = render 'series_list', series_list: @series
      - else
        No Favories added
    - else
      - if @series.any?
        = render 'series_list', series_list: @series
      - else
        No Favories added

app/views/home/search.html.haml
.container-fluid
  .col-lg-offset-1.col-lg-11
    %h2= "Search results for:  #{params[:q]}"
  .col-lg-10.col-lg-offset-1
    - if @series.any?
      = render 'series_list', series_list: @series
    - else
      No results found

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MovieDb
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-inverse
      .container-fluid
        .navbar-header
          %a.navbar-brand{:href => "/"} TV Series
        %ul.nav.navbar-nav
        = form_tag({controller: 'home', action: 'search'}, method: :get, class: 'navbar-form search-form') do
          .form-group
            = text_field_tag(:q, (params[:q] || ''), class: 'form-control', placeholder: 'Series name')
          %button.btn.btn-default{:type => "submit"} Search
    = yield

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MovieDb
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-inverse
      .container-fluid
        .navbar-header
          %a.navbar-brand{:href => "/"} TV Series
        %ul.nav.navbar-nav
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
          - else
            %li= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
            %li= link_to "Login", new_user_session_path, :class => 'navbar-link'

    - if notice
      %p.alert.alert-success= notice
    - if alert
      %p.alert.alert-danger= alert
    .container
      = yield

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>